apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-app
  name: python-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: python-app
  type: NodePort
